global defaultpath
p=defaultpath;

path([p ';C:\MATLABR11\work\testcode\'])


path([p ';C:\MATLABR11\work\testcode\'...
   ';C:\MATLABR11\work\testcode\displaytools'...
	';C:\MATLABR11\work\testcode\seismic'...
	';C:\MATLABR11\work\testcode\syntraces'...
	';C:\MATLABR11\work\testcode\synsections'...
	';C:\MATLABR11\work\testcode\utilities'...
	';C:\MATLABR11\work\testcode\velocity'...
	';C:\MATLABR11\work\testcode\migration'...
   ';C:\MATLABR11\work\testcode\raytrace'...
   ';C:\MATLABR11\work\testcode\finitedif'...
	';C:\matlabr11\work\testcode\resolution'...
	]);
