function printHeader ( obj )
%
%function printHeader ( obj )
%
%   Print header words 
%

disp (['------------------ ' ...
       obj.headerType ' filePosition = ' ...
       num2str(obj.filePosition) ...
       ' bytes ------------------']);

[m n]=size(obj.headerDefs);
   
for i = 1:m
    hv = getHeaderValue(obj,char(obj.headerDefs(i,1)));
    
    disp ([char(obj.headerDefs(i)) ...
            ': ' ...
            hv.toInterpretedString() ...
    ]);
          
%     disp ([char(obj.headerDefs(i)) ...
%         ': ' ...
%         hv.toHexString() ...
%     ]);
% 
%     disp ([char(obj.headerDefs(i)) ...
%         ': ' ...
%         hv.toString() ...
%     ]);                
end


end



