function PI_MovePickLine();
global PICKS PICKCOLOR XAXISTOP ZOOM_VALUE ZOOM_LOCKS

delete(findobj(gcf,'type','line','tag','PICKMARKER'));
delete(findobj(gcf,'type','text','tag','PICKTEXT'));
hobj=gco;
set(gcf,'windowbuttondownfcn','plotimage(''PickMoveClose'')',...
    'windowbuttonupfcn','',...
    'windowbuttonmotionfcn','');
xdat=get(hobj,'xdata');
ydat=get(hobj,'ydata');
% creating markers to
btfcn=['plotimage(''MovePickLineStart'')'];
pickmarker1=line([xdat(1)],[ydat(1)],'marker','.',...
    'buttondownfcn',btfcn,'color',PICKCOLOR,'tag','PICKMARKER',...
    'userdata',{hobj 1},'markersize',[26]);
pickmarker2=line([xdat(2)],[ydat(2)],'marker','.',...
    'buttondownfcn',btfcn,'color',PICKCOLOR,'tag','PICKMARKER',...
    'userdata',{hobj 2},'markersize',[26]);
picktext1=text(xdat(1), ydat(2),['*' num2str(xdat(1)) '*'],...
    'color',[0 0 0],'fontsize',8,'tag','PICKTEXT',...
    'verticalalignment','bottom','horizontalalignment','Left',...
    'visible','off');
textstr=str2mat(['X:' num2str(xdat(2))],['Y:' num2str(ydat(1))]);
set(hobj,'userdata',[pickmarker1 pickmarker2 picktext1],'buttondownfcn',btfcn);
